version: "3"

services:
    app:
      build:
        context: ./
      depends_on:
        - "db"
      volumes:
        - "./:/app"
        - "appvendor:/app/vendor"
      ports:
        - 80:80
    db:
      image: mysql:5.7
      restart: always
      volumes:
        - "appdata:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: hellothere
        MYSQL_DATABASE: laravel
        MYSQL_USER: prasada7
        MYSQL_PASSWORD: hellothere

volumes:
  appdata:
  appvendor:
